spring.application.name=chat-service
server.port=8085

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres-chat:5432/chat_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Multipart
spring.servlet.multipart.enabled=true

# Eureka
eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka
eureka.instance.prefer-ip-address=true

# Incident service URL (used by Feign client fallback)
incident.service.url=http://service-incident:8082

# Chatbot - Ollama
chat.bot.name=Assistant IT
chat.ai.enabled=true
spring.ai.ollama.base-url=http://host.docker.internal:11434
spring.ai.ollama.chat.model=mistral

# Keycloak resource server

# Pour valider l'issuer du token (ce que le frontend a généré)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://192.168.11.121:8080/realms/incidents-realm

# Pour fetcher les clés publiques (réseau Docker interne)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/incidents-realm/protocol/openid-connect/certs

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus

management.endpoint.health.show-details=always
management.endpoint.info.enabled=true
management.endpoint.prometheus.enabled=true

management.metrics.export.prometheus.enabled=true

# Logging
logging.level.com.gestion.incidents=DEBUG
logging.level.org.springframework.web.socket=INFO