# Server
server.port=8880

# Application name
spring.application.name=gateway-service

# ===============================
# Gateway Routes
# ===============================
spring.cloud.gateway.routes[0].id=service-incident
spring.cloud.gateway.routes[0].uri=lb://service-incident
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/incidents/**

spring.cloud.gateway.routes[1].id=service-user
spring.cloud.gateway.routes[1].uri=lb://service-user
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[2].id=comment-service
spring.cloud.gateway.routes[2].uri=lb://comment-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/commentaires/**

spring.cloud.gateway.routes[3].id=chat-service
spring.cloud.gateway.routes[3].uri=lb://chat-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/chat/**,/ws/**

# ===============================
# Eureka
# ===============================
eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka
eureka.instance.prefer-ip-address=true

# ===============================
# Keycloak / OAuth2 Resource Server
# ===============================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/incidents-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/incidents-realm/protocol/openid-connect/certs

# ===============================
# CORS (allow frontend)
# ===============================
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:3000,http://localhost:4200
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.codec.max-in-memory-size=50MB
server.netty.max-initial-line-length=65536
spring.cloud.gateway.httpclient.pool.max-connections=1000

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info,prometheus

management.endpoint.health.show-details=always
management.endpoint.info.enabled=true
management.endpoint.prometheus.enabled=true

management.metrics.export.prometheus.enabled=true

# ===============================
# Logging
# ===============================
logging.level.org.springframework.cloud.gateway=DEBUG