spring.application.name=service-user
server.port=8081

# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://postgres-user:5432/service_user_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Keycloak / OAuth2 Resource Server
# ===============================

# Pour valider l'issuer du token (ce que le frontend a généré)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/incidents-realm

# Pour fetcher les clés publiques (réseau Docker interne)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/incidents-realm/protocol/openid-connect/certs

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info,prometheus

management.endpoint.health.show-details=always
management.endpoint.info.enabled=true
management.endpoint.prometheus.enabled=true

management.metrics.export.prometheus.enabled=true

# ===============================
# Eureka
# ===============================
eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka
eureka.instance.prefer-ip-address=true