spring.application.name=service-incident
server.port=8082

# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/incidents_db
spring.datasource.username=${INCIDENT_DB_USERNAME}
spring.datasource.password=$${INCIDENT_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# MinIO (upload des captures)
# ===============================
minio.url=http://minio:9000
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket=incidents

# ===============================
# Keycloak / OAuth2 Resource Server
# ===============================

# Pour valider l'issuer du token (ce que le frontend a généré)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/incidents-realm

# Pour fetcher les clés publiques (réseau Docker interne)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/incidents-realm/protocol/openid-connect/certs

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ===============================
# Logs
# ===============================
logging.level.org.springframework=INFO
logging.level.com.microservices_project.service_incident=DEBUG

# ===============================
# Eureka
# ===============================
eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka
eureka.instance.prefer-ip-address=true